import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.scss";
import NavBar from "@/components/Navbar/Navbar";
import BackToTop from "@/components/BackToTop";
import CursorElem from "@/components/CursorElem";

const poppinsFont = Poppins({ subsets: ["latin"], weight: ["100", "200", "400", "500", "900"] });

export const metadata: Metadata = {
  title: "Bartosz Sołga - Portfolio",
  description: "Generated by create next app"
};

interface Properties {
  children: React.ReactNode;
}

export default function RootLayout({ children }: Properties) {
  return (
    <html lang="en">
      <body className={`${poppinsFont.className}`}>
        <div className="hidden md:block">
          <CursorElem />
        </div>
        <NavBar />
        {children}
        <BackToTop />
      </body>
    </html>
  );
}
