import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.scss";
import NavBar from "@/components/Navbar/Navbar";
import BackToTop from "@/components/Clickables/BackToTop";

const interFont = Poppins({ subsets: ["latin"], weight: ["100", "500", "900"] });

export const metadata: Metadata = {
  title: "Bartosz Sołga - Portfolio",
  description: "Generated by create next app",
};

interface Properties {
  children: React.ReactNode;
}

export default function RootLayout({ children }: Properties) {
  return (
    <html lang="en">
      <body className={`${interFont.className}`}>
        <NavBar />
        {children}
        <BackToTop />
      </body>
    </html>
  );
}
