import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";

const interFont = Inter({ subsets: ["latin"], weight: ["100", "500", "900"] });

export const metadata: Metadata = {
  title: "Bartosz Sołga - Portfolio",
  description: "Generated by create next app",
};

interface Properties {
  children: React.ReactNode;
}

export default function RootLayout({ children }: Properties) {
  return (
    <html lang="en">
      <body className={`${interFont.className}`}>
        {children}
      </body>
    </html>
  );
}
